### ISSUE TITLE
Tests should cover more testcases

### ISSUE THREAD

**Issue by hpez** [hpez/PHPBignum#1]
Tests for BigInt class which are located in tests/BigIntTest.php, should cover more testcases, meaning there need to be more testcases for each functionallity. Actually means improving [code coverage](https://codecov.io/gh/hpez/PHPBignum)
Any pull request improving coverage would be merged.

**Comment by falghi** [comment]
Hey I just added some test cases and it fails on some of the functions (big int sub, big int mod, and big int pow). I will submit the pull request so you can check it.

P.s. I will also submit the fixes

**Comment by hpez** [comment]
Great!

**Comment by grogy** [comment]
My pull request number #47 coverage 100% of code with tests. Can you please look it and merge when it will be ok? :-)

**Comment by hpez** [comment]
Nice job! @grogy
