### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by VictorAvelar** [hpez/PHPBignum#31]
Good morning, I saw your comment at [dev.to](https://dev.to), so to be able to help you I want to understand some of the design desitions you're making here.

1. Why you're not using PSR-4 for class autoloading?
2. Why are you requiring the composer autoload file on every class?

😄

**Comment by hpez** [comment]
To answer your first question, I agree that's a better approach, so why not create an issue or even better a pull request!
But to answer your second question, I'm not sure if there's a better alternative here.

**Comment by VictorAvelar** [comment]
I will try to draft a PR 😈 no worries.

**Comment by hpez** [comment]
Great!
