### ISSUE TITLE
Add usage to documentation

### ISSUE THREAD

**Issue by hpez** [hpez/PHPBignum#48]
Documentation should include usage samples of BigInt and BigFloat class.

**Comment by nikkolai14** [comment]
Hi! I was reading the tests on how to use this library and was thinking that on the usage documentation  it will almost be the same. Please let me know if I can help on adding this. thanks!

**Comment by hpez** [comment]
Sure, it'd be great if you make a pr for it @nikkolai14

**Comment by nikkolai14** [comment]
@hpez  thanks! will give this a shot!

**Comment by nikkolai14** [comment]
@hpez  I'm in the process of adding the "usage documentation" but I realized that there is no way of printing the result. The solution I can think of is to extend the class then create my own method but I think this extra step is not necessary. I make a [PR](https://github.com/hpez/PHPBignum/pull/50) for it. kindly check then let me know. thanks!

**Comment by nikkolai14** [comment]
@hpez Thanks for the merged for [#53](https://github.com/hpez/PHPBignum/pull/51). I can now continue with this task.
