### ISSUE TITLE
Problem with div

### ISSUE THREAD

**Issue by xavierpuyo** [hpez/PHPBignum#49]
https://github.com/hpez/PHPBignum/blob/226b107daaab2ec49f5b22c2f2460a1627c42791/tests/BigFloatTest.php#L1

    public function testDivWorks4(): void
    {
        $bigFloat1 = new BigFloat('3.1415926535898');
        $bigFloat2 = new BigFloat('180');
        $this->assertEquals(
            new BigFloat('0.01745327777777777777777777777778'),
            $bigFloat1->
            div($bigFloat2)
        );
    }

Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 hpez\bignum\BigFloat Object (
-    'number' => '0.01745327777777777777777777777778'
+    'number' => '1745.329252'
 )

**Comment by nikkolai14** [comment]
I am not good in math, but if you use a calculator to compute this the actual result is correct.

**Comment by xavierpuyo** [comment]
3.14/180=0.017 not 1745
Maybe I don’t understand something but it’s the calcul that I want to do.

**Comment by arjank** [comment]
I think I have a solution for this issue.
