### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by ankush981** [hpez/PHPBignum#6]
Hello, I've come here from Dev.to and had a query. What's the roadmap for the project ahead? Currently I see that only four arithmetic operations need implementation on BigFloat. Once these are done, is the project finished? :thinking:

**Comment by hpez** [comment]
Hi! 
Good question actually! What I'm thinking is improvements to the algorithms and adding other operations like pow (power) and sqrt (square root). The goal is making a well functional and complete calculus for bignums in PHP @ankush981

**Comment by ankush981** [comment]
I'm sorry to keep circling back to the same thing again, but will the project be done after we add `pow()` and `sqrt()`? :grin: I ask because if the project is already almost done, I might as well stay away from it. :stuck_out_tongue: However, if there are many more functions to be added, I'll feel motivated (sorry, but I have a selfish way of thinking). So, what after `pow()` and `sqrt()`? Will we develop floor, ceiling, trigonometric functions, and so on?

**Comment by hpez** [comment]
😁 yeah, just as I said the goal is to make a complete bignum calculus for PHP so it can go as far as it can! I just added the ones that came to my mind at the moment but the plan is the complete functionalities a bignum library can have.

**Comment by hpez** [comment]
I'm closing this for now, let me know if there are any other questions
